/**
 * uji-protokol-hrv.logic.test.js
 *
 * The three-block test decides whether a sensor is returned to the shop. These
 * tests exist so that decision rests on arithmetic somebody checked.
 *
 * The last block is the important one: it re-runs interval series through the
 * JavaScript and asserts the answers against numbers generated by the Python
 * pipeline itself (`scripts/make_protocol_fixture.py`). Everything above it tests
 * behaviour the fixture cannot reach — packet decoding, live beat timing, and the
 * dropout case, which cannot be expressed through Python's `cumsum` time axis.
 */

import { describe, expect, it } from 'vitest'

import fixture from './uji-protokol-hrv.fixture.json'
import { parseHeartRateMeasurement as parseTs } from './src/app/heartRateProtocol.ts'
import {
  SEGMENT_MIN_BEATS,
  beatTimes,
  classifyRrSource,
  dropouts,
  bpmGridCorrelation,
  timingResolutionMs,
  SYNTHETIC_MIN_SAMPLES,
  correctEctopic,
  judgeDeviceTest,
  meanHr,
  parseHeartRateMeasurement,
  phaseStats,
  rmssd,
  segmentYield,
} from './uji-protokol-hrv.logic.js'

const packet = (bytes) => new DataView(new Uint8Array(bytes).buffer)

/** 1/1024-second units for a given number of milliseconds. */
const units = (ms) => Math.round((ms / 1000) * 1024)
const le = (v) => [v & 0xff, (v >> 8) & 0xff]

describe('penguraian paket BLE', () => {
  it('membaca HR 8-bit tanpa field RR', () => {
    const s = parseHeartRateMeasurement(packet([0x00, 72]))
    expect(s).toEqual({ bpm: 72, hasRrIntervals: false, rrMs: [] })
  })

  it('mengubah satuan 1/1024 detik menjadi milidetik', () => {
    // 1024 units is exactly one second; 870 units is 849.609375 ms.
    const s = parseHeartRateMeasurement(packet([0x10, 60, ...le(1024), ...le(870)]))
    expect(s.hasRrIntervals).toBe(true)
    expect(s.rrMs).toEqual([1000, 849.609375])
  })

  it('melewati field Energy Expended', () => {
    // 512 units is exactly 500 ms, so the assertion cannot be confused by the
    // rounding that 1/1024-second resolution imposes on most millisecond values.
    const withEnergy = packet([0x18, 65, ...le(1200), ...le(512)])
    expect(parseHeartRateMeasurement(withEnergy).rrMs).toEqual([500])
    // Without the skip, the two energy bytes would be read as the first
    // interval and every interval after it would land one pair out of step.
    const noSkip = packet([0x10, 65, ...le(1200), ...le(512)])
    expect(parseHeartRateMeasurement(noSkip).rrMs).toEqual([1171.875, 500])
  })

  it('membaca HR 16-bit', () => {
    const s = parseHeartRateMeasurement(packet([0x11, ...le(300), ...le(units(500))]))
    expect(s.bpm).toBe(300)
    expect(s.rrMs).toEqual([500])
  })

  it('sepakat dengan salinan TypeScript milik aplikasi React', () => {
    // Two copies of this decoder exist because the standalone page loads without
    // a build step. This is what stops them drifting apart.
    const packets = [
      [0x00, 72],
      [0x01, ...le(72)],
      [0x10, 60, ...le(1024)],
      [0x10, 60, ...le(units(812)), ...le(units(799)), ...le(units(834))],
      [0x18, 65, ...le(1200), ...le(units(800))],
      [0x19, ...le(65), ...le(1200), ...le(units(800)), ...le(units(810))],
      [0x11, ...le(300), ...le(units(500))],
    ]
    for (const bytes of packets) {
      expect(parseHeartRateMeasurement(packet(bytes))).toEqual(parseTs(packet(bytes)))
    }
  })
})

describe('koreksi ektopik', () => {
  it('menandai interval di luar 300-2000 ms', () => {
    const { isOutlier } = correctEctopic([800, 250, 800, 2500, 800])
    expect(isOutlier[1]).toBe(true)
    expect(isOutlier[3]).toBe(true)
  })

  it('membandingkan terhadap nilai ASLI sebelumnya, bukan hasil koreksi', () => {
    // A long run of large intervals. Comparing against "the last accepted value"
    // would freeze the reference at 800 and condemn the entire tail; comparing
    // against the literal preceding value flags only the one real jump.
    const rr = [800, 800, 1200, 1210, 1205, 1215, 1200]
    const { isOutlier } = correctEctopic(rr)
    expect(isOutlier).toEqual([false, false, true, false, false, false, false])
  })

  it('memperbaiki dengan interpolasi, bukan dengan penghapusan', () => {
    const rr = [800, 800, 2500, 1200, 1200]
    const { corrected, isOutlier } = correctEctopic(rr)

    expect(isOutlier).toEqual([false, false, true, true, false])
    // Interpolated between the surrounding good beats at indices 1 and 4.
    expect(corrected[2]).toBeCloseTo(933.3333, 3)
    expect(corrected[3]).toBeCloseTo(1066.6667, 3)

    // The distinction is not cosmetic. Deleting the flagged beats instead would
    // make beats 1 and 4 adjacent and hand RMSSD a difference between two beats
    // that never followed one another.
    const byDeletion = rr.filter((_, i) => !isOutlier[i])
    expect(rmssd(byDeletion)).toBeCloseTo(282.84, 1)
    expect(rmssd(corrected)).toBeCloseTo(115.47, 1)
    expect(meanHr(byDeletion)).toBeCloseTo(64.29, 1)
    expect(meanHr(corrected)).toBeCloseTo(62.5, 1)
  })

  it('menahan diri di tepi deret alih-alih mengekstrapolasi', () => {
    const { corrected } = correctEctopic([2500, 800, 800, 800, 2500])
    expect(corrected[0]).toBe(800)
    expect(corrected[4]).toBe(800)
  })

  it('membiarkan deret apa adanya bila semua denyut ditandai', () => {
    const rr = [2500, 2600, 2700]
    const { corrected, isOutlier } = correctEctopic(rr)
    expect(isOutlier).toEqual([true, true, true])
    expect(corrected).toEqual(rr)
  })
})

describe('segmentasi', () => {
  /** Beats at a fixed spacing over a time range, as [t, isOutlier] arrays. */
  const beatsBetween = (from, to, step) => {
    const t = []
    for (let x = from; x < to; x += step) t.push(+x.toFixed(6))
    return t
  }

  it('menghitung jendela yang kekurangan denyut ke dalam PENYEBUT', () => {
    // Beats stop for 45 seconds in the middle — exactly what a band that slips
    // produces. Three windows survive, one is lost, and the tool must say so.
    const t = [...beatsBetween(0, 60, 0.85), ...beatsBetween(105, 150.5, 0.85)]
    const seg = segmentYield(t, t.map(() => false))

    expect(seg.total).toBe(4)
    expect(seg.droppedShort).toBe(1)
    expect(seg.eligible).toBe(3)

    // The old page skipped short windows without counting them, so this same
    // recording reported a flawless "3 / 3" and the dropout vanished.
    expect(`${seg.eligible}/${seg.total}`).not.toBe('3/3')
  })

  it('menolak jendela berisi 25 denyut (ambang 30, bukan 20)', () => {
    const t = [...beatsBetween(0, 50, 2), 61]
    expect(t.length - 1).toBe(25)
    expect(SEGMENT_MIN_BEATS).toBe(30)

    const seg = segmentYield(t, t.map(() => false))
    expect(seg.total).toBe(1)
    expect(seg.droppedShort).toBe(1)
    expect(seg.eligible).toBe(0)
  })

  it('menolak jendela dengan outlier di atas 10%', () => {
    const t = beatsBetween(0, 61, 1)
    const flags = t.map((_, i) => i < 8) // 8 of 60 in the first window = 13.3%
    const seg = segmentYield(t, flags)
    expect(seg.total).toBe(1)
    expect(seg.droppedNoisy).toBe(1)
    expect(seg.eligible).toBe(0)
  })

  it('menerima jendela dengan outlier tepat 10%', () => {
    const t = beatsBetween(0, 61, 1)
    const flags = t.map((_, i) => i < 6) // 6 of 60 = 10.0%, the boundary is inclusive
    expect(segmentYield(t, flags).eligible).toBe(1)
  })

  it('tidak menghasilkan jendela bila blok lebih pendek dari 60 detik', () => {
    const t = beatsBetween(0, 59, 0.8)
    expect(segmentYield(t, t.map(() => false)).total).toBe(0)
  })
})

describe('cap waktu denyut', () => {
  it('menyebar denyut satu paket mundur dari waktu tiba', () => {
    // The packet arrives once, carrying three beats. The last one ended now; the
    // earlier two ended one interval earlier each.
    const t = beatTimes([800, 850, 900], 10, null)
    expect(t[2]).toBeCloseTo(10, 9)
    expect(t[1]).toBeCloseTo(9.1, 9)
    expect(t[0]).toBeCloseTo(8.25, 9)
  })

  it('tetap menaik ketika paket datang terlambat', () => {
    const t = beatTimes([800, 850, 900], 10, 8.5)
    expect(t[0]).toBeGreaterThan(8.5)
    // Spacing inside the packet is preserved; the whole packet just shifts.
    expect(t[1] - t[0]).toBeCloseTo(0.85, 9)
    expect(t[2] - t[1]).toBeCloseTo(0.9, 9)
  })

  it('meninggalkan jeda nyata saat sensor berhenti mengirim', () => {
    // The point of anchoring on arrival. A clock that accumulated intervals
    // instead would close this gap and the lost minute would never show up.
    let last = null
    const t = []
    const push = (rr, arrival) => {
      const stamps = beatTimes(rr, arrival, last)
      t.push(...stamps)
      last = stamps[stamps.length - 1]
    }
    for (let i = 1; i <= 70; i++) push([850], i * 0.85)
    for (let i = 1; i <= 55; i++) push([850], 105 + i * 0.85)

    expect(t[t.length - 1] - t[0]).toBeGreaterThan(140)
    const seg = segmentYield(t, t.map(() => false))
    expect(seg.droppedShort).toBeGreaterThan(0)
    expect(seg.eligible).toBeLessThan(seg.total)
  })
})

describe('lubang rekaman', () => {
  /** Beats at a fixed spacing, with an optional silence inserted part-way. */
  const run = (nBefore, silence, nAfter, rr = 700) => {
    const t = []
    let now = 0
    for (let i = 0; i < nBefore; i++) { t.push(now); now += rr / 1000 }
    now += silence
    for (let i = 0; i < nAfter; i++) { t.push(now); now += rr / 1000 }
    return { t, rrMs: t.map(() => rr) }
  }

  it('tidak melaporkan lubang pada rekaman yang utuh', () => {
    const { t, rrMs } = run(100, 0, 0)
    const d = dropouts(t, rrMs)
    expect(d.count).toBe(0)
    expect(d.seconds).toBe(0)
    expect(d.coveragePct).toBeGreaterThan(99)
  })

  it('menemukan hening yang tidak meninggalkan jejak di gerbang outlier', () => {
    // The decisive case. Fourteen seconds of silence between two ordinary
    // 700 ms intervals: T1.5 sees nothing wrong, because neither interval is
    // out of range and neither differs from its predecessor by 20%.
    const { t, rrMs } = run(50, 14, 50)
    const { isOutlier } = correctEctopic(rrMs)
    expect(isOutlier.filter(Boolean).length).toBe(0)

    const d = dropouts(t, rrMs)
    expect(d.count).toBe(1)
    expect(d.seconds).toBeCloseTo(14.7, 1)
    expect(d.coveragePct).toBeLessThan(90)
  })

  it('tidak menghitung satu jeda sinus sebagai lubang', () => {
    // Two beats' worth of pause is within normal variation; the threshold sits
    // at 2.5 so that ordinary recordings are not condemned.
    const { t, rrMs } = run(50, 0.7, 50)
    expect(dropouts(t, rrMs).count).toBe(0)
  })

  it('cakupan turun sebanding waktu yang hilang', () => {
    const { t, rrMs } = run(50, 35, 50)   // 70 s of beats, 35 s of silence
    expect(dropouts(t, rrMs).coveragePct).toBeCloseTo(66.7, 0)
  })

  it('phaseStats membawa cakupan keluar bersama outlier', () => {
    const { t, rrMs } = run(80, 20, 80)
    const s = phaseStats(rrMs, t)
    expect(s.dropoutCount).toBe(1)
    expect(s.coveragePct).toBeLessThan(90)
    // Outlier stays clean — that is exactly why coverage has to be reported
    // beside it rather than folded into it.
    expect(s.outlierPct).toBe(0)
  })
})

describe('gerbang RR sintetis', () => {
  /** Quantise to the 1/1024 s the BLE field actually carries. */
  const toBle = (ms) => Math.round(Math.round((ms / 1000) * 1024) / 1024 * 1000 * 10) / 10

  /** Deterministic wander, so a failure is always the same failure. */
  const wander = (seed) => {
    let s = seed
    return () => {
      s = (s * 1103515245 + 12345) & 0x7fffffff
      return s / 0x7fffffff - 0.5
    }
  }

  /** `60000 / bpm` with an integer bpm — the failure mode being hunted. */
  const fabricated = (n, seed = 3) => {
    const next = wander(seed)
    let bpm = 86
    return Array.from({ length: n }, () => {
      bpm = Math.max(66, Math.min(110, bpm + next() * 3))
      return toBle(60000 / Math.round(bpm))
    })
  }

  /** Genuine intervals, quantised by the device's own clock. */
  const genuine = (n, stepMs, seed = 5) => {
    const next = wander(seed)
    let rr = 700
    return Array.from({ length: n }, () => {
      rr = 700 + (rr - 700) * 0.75 + next() * 90
      return stepMs
        ? Math.round((Math.round(rr / stepMs) * stepMs) * 10) / 10
        : toBle(rr)
    })
  }

  it('menahan putusan sebelum cukup denyut terkumpul', () => {
    const values = genuine(SYNTHETIC_MIN_SAMPLES - 1, 0)
    expect(classifyRrSource({ matches: 0, samples: values.length, values })).toBe('menilai')
  })

  it('masih menahan putusan pada 40 denyut', () => {
    // Written with the number spelled out rather than derived from the constant.
    // A test that reads SYNTHETIC_MIN_SAMPLES to build its own input moves with
    // the value it is supposed to be guarding, and keeps passing when somebody
    // lowers it — which is the "test that does not bite" the handover warns about.
    expect(SYNTHETIC_MIN_SAMPLES).toBeGreaterThan(40)
    const values = genuine(40, 0)
    expect(classifyRrSource({ matches: 0, samples: 40, values })).toBe('menilai')
  })

  it('menghukum deret yang sama dengan 60000/HR', () => {
    const values = fabricated(200)
    expect(classifyRrSource({ matches: 196, samples: 200, values })).toBe('sintetis')
  })

  it('menghukum deret buatan walau bpm yang dilaporkan sudah dihaluskan', () => {
    // Signature 1 is blind here — the packet's bpm no longer matches the bpm the
    // interval was fabricated from, so almost nothing lands within 2 ms. Only
    // the shape of the value grid gives it away.
    const values = fabricated(200)
    expect(classifyRrSource({ matches: 4, samples: 200, values })).toBe('sintetis')
  })

  it('menghukum deret yang nyaris datar', () => {
    const values = Array.from({ length: 200 }, (_, i) => 700 + (i % 3))
    expect(classifyRrSource({ matches: 2, samples: 200, values })).toBe('sintetis')
  })

  it('meloloskan deret sungguhan beresolusi halus', () => {
    const values = genuine(200, 0)
    expect(classifyRrSource({ matches: 3, samples: 200, values })).toBe('asli')
  })

  it('meloloskan deret sungguhan yang jam alatnya kasar', () => {
    // The HW9 case. Quantised at 7.6 ms, so only ~40 values are available across
    // the whole range — the old distinct-value count condemned exactly this.
    const values = genuine(200, 7.6245)
    expect(classifyRrSource({ matches: 3, samples: 200, values })).toBe('asli')
  })

  it('memisahkan kedua populasi dengan jarak yang lebar, bukan pas-pasan', () => {
    // The threshold is only defensible if nothing sits near it.
    expect(bpmGridCorrelation(fabricated(200))).toBeGreaterThan(0.9)
    expect(bpmGridCorrelation(genuine(200, 7.6245))).toBeLessThan(0.5)
    expect(bpmGridCorrelation(genuine(200, 0))).toBeLessThan(0.5)
  })

  it('melaporkan resolusi jam alat tanpa menghakiminya', () => {
    expect(timingResolutionMs(genuine(300, 7.6245))).toBeCloseTo(7.6, 0)
    expect(timingResolutionMs(genuine(300, 0))).toBeLessThan(3)
  })
})

describe('kriteria putusan terkunci', () => {
  const block = (over) => ({
    nBeats: 200, outlierPct: 4, segEligible: 5, segTotal: 6,
    segDroppedShort: 0, segDroppedNoisy: 1, meanHr: 88,
    rmssd: 30, rmssdSegments: [30], rmssdMedian: 30, ...over,
  })
  const rest = (over) => block({ meanHr: 70, rmssdMedian: 35, ...over })

  it('menolak menilai blok tertekan yang lebih pendek dari satu jendela', () => {
    expect(judgeDeviceTest(rest(), block({ segTotal: 0 })).level).toBe('kurang-data')
  })

  it('menyatakan GAGAL di atas 20% outlier', () => {
    expect(judgeDeviceTest(rest(), block({ outlierPct: 25 })).level).toBe('gagal')
  })

  it('menyatakan GAGAL bila tidak ada satu pun segmen layak', () => {
    expect(judgeDeviceTest(rest(), block({ outlierPct: 3, segEligible: 0 })).level).toBe('gagal')
  })

  it('menyatakan BATAS pada 10-20% outlier', () => {
    expect(judgeDeviceTest(rest(), block({ outlierPct: 15 })).level).toBe('batas')
  })

  it('menyatakan BATAS bila hasil segmen di bawah 60%', () => {
    expect(judgeDeviceTest(rest(), block({ segEligible: 2, segTotal: 6 })).level).toBe('batas')
  })

  it('menyatakan LULUS hanya bila RMSSD istirahat juga masuk akal', () => {
    const v = judgeDeviceTest(rest({ rmssdMedian: 35 }), block())
    expect(v.level).toBe('lulus')
  })

  it('menahan kelulusan ketika RMSSD istirahat di luar 20-60 ms', () => {
    // The case a gate built only on outliers cannot see: a smooth but
    // systematically wrong interval series passes every jump check.
    expect(judgeDeviceTest(rest({ rmssdMedian: 140 }), block()).level).toBe('batas')
    expect(judgeDeviceTest(rest({ rmssdMedian: 4 }), block()).level).toBe('batas')
  })

  it('memberi tahu bila HR tidak naik, dan menyalahkan protokol bukan sensor', () => {
    const v = judgeDeviceTest(rest({ meanHr: 88 }), block({ meanHr: 88 }))
    expect(v.level).toBe('lulus')
    expect(v.detail).toMatch(/belum benar-benar tertekan/)
  })

  it('menahan kelulusan ketika blok istirahat belum menghasilkan RMSSD', () => {
    expect(judgeDeviceTest(null, block()).level).toBe('batas')
  })
})

describe('cocok dengan pipeline Python', () => {
  const cumsumSec = (rr) => {
    let acc = 0
    return rr.map((v) => (acc += v) / 1000)
  }

  for (const kasus of fixture.cases) {
    describe(kasus.name, () => {
      const { corrected, isOutlier } = correctEctopic(kasus.rr_ms)
      const e = kasus.expected

      it('menandai denyut yang sama persis', () => {
        expect(isOutlier).toEqual(e.is_outlier)
      })

      it('menghasilkan nilai koreksi yang sama', () => {
        expect(corrected.length).toBe(e.corrected.length)
        corrected.forEach((v, i) => expect(v).toBeCloseTo(e.corrected[i], 6))
      })

      it('menghasilkan mean HR dan RMSSD yang sama', () => {
        expect(meanHr(corrected)).toBeCloseTo(e.mean_hr, 6)
        expect(rmssd(corrected)).toBeCloseTo(e.rmssd, 6)
      })

      it('menjendelakan dan menggerbang dengan cara yang sama', () => {
        const seg = segmentYield(cumsumSec(corrected), isOutlier)
        expect(seg.eligible).toBe(e.n_kept)
        expect(seg.droppedShort).toBe(e.n_dropped_short)
        expect(seg.droppedNoisy).toBe(e.n_dropped_noisy)
        expect(seg.total).toBe(e.n_total)

        seg.windows.forEach((w, i) => {
          const ref = e.segments[i]
          expect(w.startSec).toBeCloseTo(ref.start_sec, 6)
          expect(w.indices.length).toBe(ref.n_beats)
          expect(w.outlierRatio).toBeCloseTo(ref.outlier_ratio, 9)
        })
      })

      it('menghasilkan RMSSD per segmen yang sama', () => {
        const stats = phaseStats(kasus.rr_ms, cumsumSec(corrected))
        expect(stats.rmssdSegments.length).toBe(e.segments.length)
        stats.rmssdSegments.forEach((v, i) => expect(v).toBeCloseTo(e.segments[i].rmssd, 6))
        expect(stats.outlierPct).toBeCloseTo(e.outlier_ratio * 100, 9)
      })
    })
  }
})
